import './globals.css';
import { Inter } from 'next/font/google';
import { Layout } from '../components/index';

import { Toaster } from 'react-hot-toast';
import { StateContext } from '../context/StateContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'E-piano store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContext>
          <Layout>
            <Toaster />
            {children}
          </Layout>
        </StateContext>
      </body>
    </html>
  )
}
